# Generated by Django 5.0 on 2024-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
