# Generated by Django 5.0 on 2024-01-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(blank=True, default='01749497676', unique=True),
        ),
    ]
