# Generated by Django 5.0 on 2024-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, upload_to='account/images/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
