# Generated by Django 5.0 on 2024-01-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_address_alter_useraccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='account/images/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
