# Generated by Django 5.0 on 2024-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='all_seats',
            field=models.ManyToManyField(blank=True, related_name='trains', to='train.seat'),
        ),
    ]
