# Generated by Django 5.0 on 2024-01-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='end_station',
        ),
        migrations.RemoveField(
            model_name='train',
            name='start_station',
        ),
        migrations.AddField(
            model_name='train',
            name='station',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station', to='train.station'),
        ),
    ]
