# Generated by Django 5.0 on 2024-01-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_train_all_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='train',
        ),
    ]
