# Generated by Django 5.0 on 2024-01-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_alter_seat_options_alter_train_train_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='train.train'),
        ),
    ]
